CREATE TABLE animal (
    id BIGINT auto_increment PRIMARY KEY,
    nome VARCHAR(50),
    tipo VARCHAR(50),
    raca VARCHAR(50),
    idade INT,
    descricao VARCHAR(100)
);

INSERT INTO animal (nome, idade, tipo, raca, descricao) VALUES
('Buddy', 3, 'Cachorro', 'Golden Retriever', 'Amigável e cheio de energia à procura de um lar amoroso.'),
('Mittens', 2, 'Gato', 'Tabby Cat', 'Brincalhão e carinhoso que adora carinho.'),
('Charlie', 5, 'Cachorro', 'Beagle', 'Leal e curioso, ótimo com famílias.'),
('Max', 4, 'Cachorro', 'German Shepherd', 'Inteligente e protetor, precisa de um dono ativo.'),
('Toby', 3, 'Cachorro', 'Shih Tzu', 'Muito carinhoso, adora brincar com crianças'),
('Luna', 2, 'Gato', 'Siamês', 'Gata tranquila e curiosa, gosta de janelas'),
('Thor', 5, 'Cachorro', 'Labrador', 'Cheio de energia, ótimo para caminhadas'),
('Maya', 1, 'Cachorro', 'Poodle', 'Inteligente e fácil de treinar'),
('Romeu', 4, 'Gato', 'Persa', 'Gato peludo e dócil, ama colo'),
('Nina', 2, 'Cachorro', 'Yorkshire', 'Pequena, mas muito protetora'),
('Max', 6, 'Cachorro', 'Bulldog', 'Calmo, companheiro ideal para idosos'),
('Mel', 1, 'Cachorro', 'SRD', 'Filhote resgatada, muito brincalhona'),
('Simba', 3, 'Gato', 'Maine Coon', 'Grande, peludo e extremamente dócil'),
('Bidu', 7, 'Cachorro', 'Beagle', 'Adora farejar e passear'),
('Pipoca', 2, 'Pássaro', 'Calopsita', 'Pássaro que assobia melodias'),
('Jade', 4, 'Cachorro', 'Golden Retriever', 'Muito sociável com outros animais'),
('Fred', 3, 'Cachorro', 'Dálmata', 'Animado, com manchas únicas'),
('Belinha', 5, 'Cachorro', 'Pinscher', 'Pequena, mas valente e vigilante'),
('Biscoito', 1, 'Gato', 'Angorá', 'Gato de pelo comprido, brincalhão'),
('Rex', 8, 'Cachorro', 'Pastor Alemão', 'Ótimo cão de guarda, leal'),
('Lili', 2, 'Cachorro', 'Maltes', 'Delicada, ótima para apartamentos'),
('Mimi', 6, 'Gato', 'SRD', 'Gata independente, caçadora de insetos'),
('Bob', 4, 'Cachorro', 'Cocker Spaniel', 'Orelhas longas e olhar carinhoso'),
('Amora', 1, 'Cachorro', 'Husky Siberiano', 'Cheia de energia e olhos azuis'),
('Chico', 3, 'Pássaro', 'Papagaio', 'Fala palavras e canta músicas'),
('Fiona', 5, 'Cachorro', 'Dachshund', 'Corpo comprido, muito esperta'),
('Nick', 2, 'Cachorro', 'Schnauzer', 'Barba marcante, alegre'),
('Nega', 7, 'Cachorro', 'SRD', 'Cachorra preta, muito fiel'),
('Léo', 1, 'Gato', 'Ragdoll', 'Gato de olhos azuis, super dócil'),
('Sol', 3, 'Cachorro', 'Border Collie', 'Muito inteligente e ativo'),
('Guga', 4, 'Cachorro', 'Lhasa Apso', 'Companheiro e silencioso'),
('Zara', 2, 'Cachorro', 'Spitz Alemão', 'Peluda, pequena e brincalhona'),
('Cacau', 5, 'Roedor', 'Hamster', 'Pequeno e adora rodinhas'),
('Malu', 1, 'Cachorro', 'Chihuahua', 'Muito pequena e protetora'),
('Kiko', 6, 'Cachorro', 'SRD', 'Cão de porte médio, dócil'),
('Lola', 2, 'Gato', 'Scottish Fold', 'Orelhas dobradas, tranquila'),
('Tigrão', 3, 'Gato', 'SRD', 'Gato listrado, caçador nato'),
('Pingo', 4, 'Cachorro', 'Pug', 'Focinho achatado, engraçado'),
('Tata', 7, 'Cachorro', 'Shar Pei', 'Pele enrugada, muito calmo'),
('Billy', 1, 'Pássaro', 'Canário', 'Pássaro amarelo, canta muito'),
('Bela', 2, 'Cachorro', 'Weimaraner', 'Olhos claros, atlética'),
('Duque', 5, 'Cachorro', 'Boxer', 'Forte, brincalhão e protetor'),
('Maggie', 6, 'Cachorro', 'Buldogue Francês', 'Baixinha, ronca bastante'),
('Nino', 2, 'Gato', 'SRD', 'Gato preto, muito ativo'),
('Fofão', 3, 'Gato', 'Angorá', 'Pelo longo e macio'),
('Juju', 1, 'Pássaro', 'Cacatua', 'Pássaro branco, gosta de companhia'),
('Teca', 5, 'Cachorro', 'Shar Pei', 'Muito carinhosa, adora dormir'),
('Pipoca', 2, 'Roedor', 'SRD', 'Hamster muito ativo à noite'),
('Snow', 4, 'Cachorro', 'Samoyeda', 'Pelagem branca e sorriso marcante'),
('Lulu', 3, 'Cachorro', 'Poodle Toy', 'Pequena, adora colo'),
('Bob', 2, 'Cachorro', 'Pastor Belga', 'Inteligente e protetor'),
('Gata', 6, 'Gato', 'SRD', 'Gata cinza, muito esperta'),
('Tigrinha', 1, 'Gato', 'SRD', 'Filhote de gato, listrada e brincalhona'),
('Floquinho', 2, 'Cachorro', 'Bichon Frisé', 'Branco, peludo e alegre'),
('Spike', 3, 'Cachorro', 'Rottweiler', 'Grande, protetor e dócil com a família');